# Generated by Django 3.0.3 on 2020-04-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idn', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_confirm', models.DateField()),
                ('case_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('details', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='covidapp.Patient')),
            ],
        ),
    ]
