# Generated by Django 3.0.3 on 2020-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20200403_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
