# Generated by Django 3.0.3 on 2020-04-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20200403_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='idn',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
