# Generated by Django 3.0.3 on 2020-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_auto_20200420_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, default='n', max_length=300, null=True),
        ),
    ]
