# Generated by Django 3.0.3 on 2020-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0005_location_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
