# Generated by Django 3.0.3 on 2020-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_auto_20200429_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='grid_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='grid_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
