# Generated by Django 3.0.3 on 2020-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0007_auto_20200429_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='covidapp.Patient'),
        ),
    ]
