# Generated by Django 3.0.3 on 2020-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0009_locationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtemplate',
            name='grid_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtemplate',
            name='grid_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
